services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beatbox
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  lavalink:
    build: ./lavalink
    ports:
      - "2333:2333"

volumes:
  pgdata:
